### ISSUE TITLE
Getting Table 'elepy-test.elepy_users' doesn't exist

### ISSUE THREAD

**Issue by sawrabh77** [RyanSusana/elepy#106]
Hi, everyone, I am trying out this framework, but I am getting the error "Table 'elepy-test.elepy_users' doesn't exist". I have created an empty MySQL database named "elepy-test'.

I have created a spring boot application, [here](https://github.com/sawrabh77/ElepyCMS) and have used following dependencies for elepy:
<dependency>
	<groupId>com.elepy</groupId>
	<artifactId>elepy-basic</artifactId>
	<version>2.5.3</version>
</dependency>
<dependency>
	<groupId>com.elepy</groupId>
	<artifactId>elepy-sparkjava</artifactId>
	<version>2.5.3</version>
</dependency>
<dependency>
	<artifactId>elepy-hibernate</artifactId>
	<groupId>com.elepy</groupId>
	<version>2.5.3</version>
</dependency>

Is there any other way to do it, or am I missing any step, any help is much appreciated.

**Comment by sawrabh77** [comment]
Hi @RyanSusana, please have a look at the issue I am facing, any help is much appreciated.

**Comment by RyanSusana** [comment]
Hi, sorry for the late reply.

Right now I'm actively developing version 3. Maybe that's a plausible fix for now?
