### ISSUE TITLE
RestModel cannot be resolved to a typeJava(16777218)

### ISSUE THREAD

**Issue by direstrepo24** [RyanSusana/elepy#107]
I have problem, already clean, but RestModel cannot be resolved to a typeJava(16777218)
@RestModel(name = "Products", path = "/products")
public class Product {
    @Identifier
    private String productId;
.....

version: 3.0.0-alpha-18

**Comment by RyanSusana** [comment]
`@RestModel` has been renamed to `@Model` in version 3 alpha
