### ISSUE TITLE
compilation failing on master 

### ISSUE THREAD

**Issue by jariwalaPranav** [RyanSusana/elepy#109]
following files are missing from master branch
- com.elepy.dao.parser.EleQueryLexer
- com.elepy.dao.parser.EleQueryParser
- ExpressionContext

P.S - @RyanSusana really like your CMS. I went through the code but wasn't able to run the application as the above files are missing.  Would really appreciate it if you can look into this at the earliest possible.  I wanted to Elepy as a CMS solution to my team

**Comment by RyanSusana** [comment]
Hi,

You need to run the antlr4 plugin first (undocumented☹️).

This generates the necessary classes.
