### ISSUE TITLE
404 Not  Found

### ISSUE THREAD

**Issue by kparysz** [RyanSusana/elepy#133]
Hey, 
I want to use 3.0.0-alpha-28 version. When I configure app like this:

```
        new Elepy()
                .withPort(7777)
                .addConfiguration(AdminPanel.newAdminPanel())
                .addConfiguration(MongoConfiguration.inMemory())
                .addModel(Product.class)
                .start();
```

When I open http://localhost:7777/ I see 404 Not found

JDK version 11
Dependecies: elepy-basic elepy-mongo mongo-java-server

Did I miss something?

**Comment by RyanSusana** [comment]
It's working. 

Go to http://localhost/elepy/admin/
