### ISSUE TITLE
Certificate error when visiting the website

### ISSUE THREAD

**Issue by nicojs** [RyanSusana/elepy#34]
It seems that I can't visit the website: https://elepy.com/

![image](https://user-images.githubusercontent.com/1828233/52850478-e05f6a80-3113-11e9-9eb0-6d0718b5adc0.png)

**Comment by RyanSusana** [comment]
Hello @nicojs is this problem still happening? I can't reproduce.
<img width="777" alt="screenshot 2019-02-15 at 15 36 21" src="https://user-images.githubusercontent.com/1254351/52863216-8d97aa00-3137-11e9-9051-d8110dc6587d.png">

**Comment by RyanSusana** [comment]
Hello @nicojs  I was just on the phone with Sophos.

They will re-assess the documentation site.

**Comment by nicojs** [comment]
Great! At this moment the problem is still occurring. I will try to check back regularly and keep you up-to-date.

**Comment by RyanSusana** [comment]
Closed and reopened to put it on the board, because Sophos hasn't replied yet

**Comment by nicojs** [comment]
Good news! 

![image](https://user-images.githubusercontent.com/1828233/54355230-cd7b7f80-4658-11e9-8f9c-1e3d8d4020c7.png)

😍 

I'm happy, so feel free to close this issue for me.

**Comment by RyanSusana** [comment]
Cheers!
