### ISSUE TITLE
A /uploads for the AdminPanel

### ISSUE THREAD

**Issue by RyanSusana** [RyanSusana/elepy#39]
Provide a way to upload and query binaries to Elepy.
Let it be able to mount to a file system.

**Comment by RyanSusana** [comment]
Done

**Comment by furbykk** [comment]
how can i upload  a file through admin panel? i cannot find a add button

**Comment by RyanSusana** [comment]
File uploads can be done by having a [FileReference](https://docs.elepy.com/#/annotations/data-types?id=filereference) field.
