### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by furbykk** [RyanSusana/elepy#76]
@RyanSusana How can we do pagination using rest api? please list the query parameters supported. 

I checked the source code, i found pageNumber and pageSize. But how can we do a desc order

**Comment by RyanSusana** [comment]
`/modelName?sort=propertyName,DESCENDING`


This should be documented. Will add it to the documentation soon. Thanks :D

**Comment by RyanSusana** [comment]
OpenAPI generation  is marked for version 3
