### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by furbykk** [RyanSusana/elepy#77]
I used to be able to upload file by @FileReference, but after I updated to 2.2.9, it throws error "No Fileservice configured. "

<img width="1440" alt="Screen Shot 2019-10-12 at 18 32 44" src="https://user-images.githubusercontent.com/43336582/66700071-35916180-ed1f-11e9-9a27-2160ed5ba5a5.png">

And I have added this line to my main.
.withFileService(new DefaultFileService())

**Comment by RyanSusana** [comment]
`new DefaultService()` is what throws that:
https://github.com/RyanSusana/elepy/blob/master/core/src/main/java/com/elepy/uploads/DefaultFileService.java#L33-L35

**Comment by furbykk** [comment]
But it also throws this error without this line. @RyanSusana

**Comment by furbykk** [comment]
I was using 2.2.9,  Now I have to revert back to 2.0.4

**Comment by furbykk** [comment]
Is this issue solved?

**Comment by RyanSusana** [comment]
Yes!
