### ISSUE TITLE
@Date field stores null value

### ISSUE THREAD

**Issue by furbykk** [RyanSusana/elepy#82]
@RyanSusana @Date field will give current date as the default value, but it only saved null without update this field.  
<img width="1308" alt="Screen Shot 2019-11-06 at 13 38 44" src="https://user-images.githubusercontent.com/43336582/68271222-d82cce00-009a-11ea-8845-bed103256a16.png">
<img width="989" alt="Screen Shot 2019-11-06 at 13 38 59" src="https://user-images.githubusercontent.com/43336582/68271227-db27be80-009a-11ea-8027-affeaef15ba8.png">

**Comment by RyanSusana** [comment]
#83
