### ISSUE TITLE
@Date field saved null value

### ISSUE THREAD

**Issue by furbykk** [RyanSusana/elepy#83]
@RyanSusana 

@Date field will have a default value when adding a model object. but the default value will not be saved to database without updating this field. 
<img width="1308" alt="Screen Shot 2019-11-06 at 13 38 44" src="https://user-images.githubusercontent.com/43336582/68271518-c0097e80-009b-11ea-87b9-eca35442fe71.png">
<img width="989" alt="Screen Shot 2019-11-06 at 13 38 59" src="https://user-images.githubusercontent.com/43336582/68271522-c3046f00-009b-11ea-91f9-e98cabc39343.png">

**Comment by RyanSusana** [comment]
Fixed in version 2.5.3
