### ISSUE TITLE
Evaluators

### ISSUE THREAD

**Issue by furbykk** [RyanSusana/elepy#86]
Hi @RyanSusana 

I notice in the latest version 2.5.0, you deprecated Evaluators annotations, how we add customized validation then?

**Comment by RyanSusana** [comment]
Hi @furbykk ,
You can use Java Bean Validation to create custom annotations.

Here's an example
<img width="643" alt="Screenshot 2019-11-26 at 13 39 44" src="https://user-images.githubusercontent.com/1254351/69634297-36bdea00-1052-11ea-9d8f-fc40883970a0.png">
