### ISSUE TITLE
Item with predefined values

### ISSUE THREAD

**Issue by kparysz** [RyanSusana/elepy#96]
Hi,
I did not find better place to ask about it so sorry if it is not right place.

I would like to create component in RestModel class which contains values from database.

I know that I can use enums to create Dropdown list, but I would like to have dropdown list with  values which are defined in external source. 

Is that possible with Elepy?

**Comment by RyanSusana** [comment]
Hi @kparysz ,

This feature was implemented in an alpha version of Elepy 3, where the `@RestModel` annotation doesn't exist anymore (replaced by `@Model`).

The annotation in version 3 is called `@Reference(to = YourOtherModel.class)`

**Comment by RyanSusana** [comment]
Be aware that version 3 is still in Alpha and is subject to some breaking changes

**Comment by kparysz** [comment]
Thank you so much. This is what I was looking for!

Do you have some date that 3.0 will be released?

**Comment by RyanSusana** [comment]
Right now I'm taking it one day at a time. 

Rewriting/breaking flawed interfaces. Don't have a release date for 3-stable yet.
