### ISSUE TITLE
@Update more than one "resource"

### ISSUE THREAD

**Issue by kparysz** [RyanSusana/elepy#97]
Hi, 

I have a two @Model() (First::class ans Second:class) in my project. I would like to insert a few items to Second table when I finish creating First item in Admin Panel. I wanted to achieve this using @Update/@Create but there is no way to get Crud<Second>. 

I hope it is understandable for you.

Do you use some discord or another place for supporting instead of creating issue on Github?

Thanks

**Comment by RyanSusana** [comment]
You can use `@Inject` Crud<Second>

**Comment by kparysz** [comment]
Basically I would like to be contributor because it is really nice project! But first I would like to have better knowledge about elepy and js itself. 

If I may ask about @Reference. When I use @Reference on object it inserts just String. Is it intended? I know that @Reference is in alpha version and it can not work fully as you want do it. 

Thank you for your help again! I really appreciate it!

**Comment by RyanSusana** [comment]
I invite you to! Thanks for the support 😃 

That is indeed the intended behavior for references.
